"""SQLAlchemy declarative base and shared column conventions.

Two things are established here that are painful to retrofit:

1. **A naming convention for constraints.** Without it, PostgreSQL invents
   names for indexes and constraints, and Alembic then cannot reliably drop or
   alter them — ``downgrade()`` breaks in ways that only appear months later.
2. **Timestamps are always ``TIMESTAMPTZ`` and always UTC**, matching
   ``Domain-Model.md``. Server-side defaults are used so a row's timestamp
   comes from the database clock, not from whichever machine happened to run
   the code.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import DateTime, MetaData, func, text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

#: Deterministic names for every constraint and index Alembic will manage.
NAMING_CONVENTION: dict[str, str] = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Declarative base for every ORM model."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)

    type_annotation_map: dict[Any, Any] = {  # noqa: RUF012
        dict[str, Any]: JSONB,
    }


def uuid_pk() -> Mapped[uuid.UUID]:
    """A UUID v4 primary key generated by the database.

    Generated server-side via ``gen_random_uuid()`` (pgcrypto) so ids are
    assigned consistently regardless of which process inserts the row.
    """
    return mapped_column(
        PG_UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )


def created_at_column() -> Mapped[datetime]:
    """A UTC creation timestamp, defaulted by the database clock."""
    return mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        index=True,
    )


def updated_at_column() -> Mapped[datetime]:
    """A UTC modification timestamp, refreshed on every UPDATE."""
    return mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )


class TimestampMixin:
    """Adds ``created_at`` / ``updated_at`` to a model."""

    created_at: Mapped[datetime] = created_at_column()
    updated_at: Mapped[datetime] = updated_at_column()
