"""m04 contact messages

Revision ID: a9f1f2a2df41
Revises: 9bedd98bd283
Create Date: 2026-08-13 15:10:34.170655+00:00

Every revision must be reversible: `downgrade()` is not optional. A migration
that cannot be rolled back is a migration you cannot safely deploy.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "a9f1f2a2df41"
down_revision: str | None = "9bedd98bd283"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contact_messages",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("subject", sa.String(length=200), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=256), nullable=True),
        sa.Column("handled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "char_length(message) >= 10", name=op.f("ck_contact_messages_message_min_length")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contact_messages")),
    )
    op.create_index(
        "ix_contact_messages_created_at_handled_at",
        "contact_messages",
        ["created_at", "handled_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_contact_messages_created_at_handled_at", table_name="contact_messages")
    op.drop_table("contact_messages")
    # ### end Alembic commands ###
