"""m02 initial schema

Revision ID: 9bedd98bd283
Revises:
Create Date: 2026-08-12 19:03:36.945218+00:00

Every revision must be reversible: `downgrade()` is not optional. A migration
that cannot be rolled back is a migration you cannot safely deploy.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "9bedd98bd283"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


#: PostgreSQL extensions this schema depends on.
#:
#: Created here, in the migration, rather than only in docker/postgres/init/,
#: because that init directory runs only for the Docker dev stack. CI uses a
#: bare postgres service container and a native Windows install has no init
#: hooks at all - in both cases gen_random_uuid() and citext would be missing
#: and every table creation below would fail.
EXTENSIONS: tuple[str, ...] = (
    "pgcrypto",   # gen_random_uuid() for UUID primary keys
    "citext",     # case-insensitive username / email
    "pg_trgm",    # trigram indexes backing the search endpoint
    "btree_gin",  # composite scalar + GIN indexes
)

#: Native enum types created implicitly by the table definitions below.
#:
#: Alembic's autogenerate creates these on upgrade but never drops them, so a
#: downgrade would leave them behind and the next upgrade would fail with
#: "type already exists". Dropping them explicitly is what makes this migration
#: genuinely reversible.
ENUM_TYPES: tuple[str, ...] = (
    "approval_state",
    "asset_kind",
    "camera_face",
    "device_status",
    "image_source",
    "image_status",
    "macro_stage",
    "membership_role",
    "membership_status",
    "model_kind",
    "notification_type",
    "professional_role",
    "project_status",
    "remark_type",
    "report_format",
    "report_kind",
    "report_status",
    "severity",
    "visibility",
)


def upgrade() -> None:
    """Apply the schema change."""
    for extension in EXTENSIONS:
        op.execute(f'CREATE EXTENSION IF NOT EXISTS "{extension}"')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_models",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("kind", sa.Enum("classifier", "detector", name="model_kind"), nullable=False),
        sa.Column("architecture", sa.String(length=48), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("framework", sa.String(length=32), server_default="pytorch", nullable=False),
        sa.Column("weights_key", sa.Text(), nullable=True),
        sa.Column(
            "class_names",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("input_size", sa.Integer(), nullable=True),
        sa.Column(
            "metrics",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("trained_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_models")),
        sa.UniqueConstraint("name", "version", name="uq_ai_models_name_version"),
    )
    op.create_index(
        "uq_ai_models_active_per_kind",
        "ai_models",
        ["kind"],
        unique=True,
        postgresql_where=sa.text("is_active"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("username", postgresql.CITEXT(), nullable=False),
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("full_name", sa.String(length=120), nullable=False),
        sa.Column(
            "professional_role",
            sa.Enum(
                "manager",
                "project_handler",
                "engineer",
                "architect",
                "foreman",
                "contractor",
                "surveyor",
                "home_owner",
                "student",
                "other",
                name="professional_role",
            ),
            nullable=False,
        ),
        sa.Column(
            "profile_visibility",
            sa.Enum("public", "private", name="visibility"),
            server_default="public",
            nullable=False,
        ),
        sa.Column("company", sa.String(length=160), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("avatar_key", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("position('@' in email) > 1", name=op.f("ck_users_email_shape")),
        sa.CheckConstraint(
            "char_length(username) BETWEEN 3 AND 30", name=op.f("ck_users_username_length")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_index(op.f("ix_users_created_at"), "users", ["created_at"], unique=False)
    op.create_index(
        "ix_users_full_name_trgm",
        "users",
        ["full_name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"full_name": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_users_username_trgm",
        "users",
        ["username"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"username": "gin_trgm_ops"},
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("project_code", sa.String(length=8), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("intended_use", sa.String(length=160), nullable=True),
        sa.Column("location_label", sa.String(length=240), nullable=False),
        sa.Column("latitude", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("deadline_date", sa.Date(), nullable=False),
        sa.Column("worker_count", sa.Integer(), nullable=True),
        sa.Column(
            "visibility",
            sa.Enum("public", "private", name="visibility"),
            server_default="private",
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "active", "inactive", "delayed", "completed", "archived", name="project_status"
            ),
            server_default="active",
            nullable=False,
        ),
        sa.Column(
            "approval_state",
            sa.Enum("not_ready", "awaiting_inspection", "approved", name="approval_state"),
            server_default="not_ready",
            nullable=False,
        ),
        sa.Column(
            "progress_pct",
            sa.Numeric(precision=5, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "macro_stage",
            sa.Enum(
                "foundation", "framing", "roofing", "finishing", "approval", name="macro_stage"
            ),
            nullable=True,
        ),
        sa.Column("window_mode", sa.String(length=16), server_default="daily", nullable=False),
        sa.Column("timezone", sa.String(length=64), server_default="Asia/Manila", nullable=False),
        sa.Column("last_capture_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_by", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("inspection_notes", sa.Text(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "progress_pct <= 80 OR approval_state = 'approved'",
            name=op.f("ck_projects_machine_ceiling_requires_approval"),
        ),
        sa.CheckConstraint(
            "project_code ~ '^[A-Z]{2,5}_[0-9]{2}$'", name=op.f("ck_projects_project_code_format")
        ),
        sa.CheckConstraint(
            "window_mode IN ('daily','weekly')", name=op.f("ck_projects_window_mode_valid")
        ),
        sa.CheckConstraint(
            "deadline_date >= start_date", name=op.f("ck_projects_deadline_after_start")
        ),
        sa.CheckConstraint("latitude BETWEEN -90 AND 90", name=op.f("ck_projects_latitude_range")),
        sa.CheckConstraint(
            "longitude BETWEEN -180 AND 180", name=op.f("ck_projects_longitude_range")
        ),
        sa.CheckConstraint(
            "progress_pct BETWEEN 0 AND 100", name=op.f("ck_projects_progress_range")
        ),
        sa.CheckConstraint(
            "worker_count IS NULL OR worker_count >= 0",
            name=op.f("ck_projects_worker_count_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["users.id"],
            name=op.f("fk_projects_approved_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_projects_owner_id_users"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
        sa.UniqueConstraint("project_code", name=op.f("uq_projects_project_code")),
    )
    op.create_index(op.f("ix_projects_created_at"), "projects", ["created_at"], unique=False)
    op.create_index(
        "ix_projects_latitude_longitude", "projects", ["latitude", "longitude"], unique=False
    )
    op.create_index(
        "ix_projects_location_label_trgm",
        "projects",
        ["location_label"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"location_label": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_projects_name_trgm",
        "projects",
        ["name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.create_index("ix_projects_owner_id", "projects", ["owner_id"], unique=False)
    op.create_index(
        "ix_projects_visibility_status", "projects", ["visibility", "status"], unique=False
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("family_id", sa.UUID(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_agent", sa.String(length=256), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refresh_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_refresh_tokens_token_hash")),
    )
    op.create_index("ix_refresh_tokens_expires_at", "refresh_tokens", ["expires_at"], unique=False)
    op.create_index(
        "ix_refresh_tokens_user_id_family_id",
        "refresh_tokens",
        ["user_id", "family_id"],
        unique=False,
    )
    op.create_table(
        "devices",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("device_name", sa.String(length=48), nullable=False),
        sa.Column(
            "face",
            sa.Enum("front", "front_diagonal", "back", "back_diagonal", name="camera_face"),
            nullable=False,
        ),
        sa.Column(
            "weight",
            sa.Numeric(precision=3, scale=2),
            server_default=sa.text("1.0"),
            nullable=False,
        ),
        sa.Column("secret_hash", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("unpaired", "paired", "online", "offline", "revoked", name="device_status"),
            server_default="paired",
            nullable=False,
        ),
        sa.Column("firmware_version", sa.String(length=32), nullable=True),
        sa.Column("hardware_id", sa.String(length=64), nullable=True),
        sa.Column(
            "capture_schedule",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text(
                '\'{"times": ["07:00", "16:00"], "timezone": "Asia/Manila"}\'::jsonb'
            ),
            nullable=False,
        ),
        sa.Column("homography", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("roi_polygon", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_battery_mv", sa.Integer(), nullable=True),
        sa.Column("last_rssi_dbm", sa.Integer(), nullable=True),
        sa.Column("paired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "device_name ~ '^ESP_[A-Z]{2,5}_[0-9]{2}_(F|FD|B|BD)[0-9]?$'",
            name=op.f("ck_devices_device_name_format"),
        ),
        sa.CheckConstraint("weight > 0 AND weight <= 5", name=op.f("ck_devices_weight_range")),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_devices_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_devices")),
        sa.UniqueConstraint("device_name", name=op.f("uq_devices_device_name")),
        sa.UniqueConstraint("project_id", "face", name="uq_devices_project_face"),
    )
    op.create_index(op.f("ix_devices_created_at"), "devices", ["created_at"], unique=False)
    op.create_index("ix_devices_project_id", "devices", ["project_id"], unique=False)
    op.create_index(
        "ix_devices_status_last_seen_at", "devices", ["status", "last_seen_at"], unique=False
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column(
            "notification_type",
            sa.Enum(
                "inspection_required",
                "delay",
                "device_offline",
                "collab_invite",
                "report_ready",
                "regression",
                "low_battery",
                name="notification_type",
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_notifications_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notifications_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index(
        "ix_notifications_user_id_read_at", "notifications", ["user_id", "read_at"], unique=False
    )
    op.create_table(
        "project_members",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "membership_role",
            sa.Enum(
                "owner",
                "manager",
                "engineer",
                "editor",
                "collaborator",
                "employee",
                "viewer",
                name="membership_role",
            ),
            nullable=False,
        ),
        sa.Column(
            "membership_status",
            sa.Enum("pending", "accepted", "revoked", name="membership_status"),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("invited_by", sa.UUID(), nullable=True),
        sa.Column("invited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["invited_by"],
            ["users.id"],
            name=op.f("fk_project_members_invited_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_project_members_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_project_members_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_members")),
        sa.UniqueConstraint("project_id", "user_id", name="uq_project_members_project_user"),
    )
    op.create_index(
        "ix_project_members_user_id_status",
        "project_members",
        ["user_id", "membership_status"],
        unique=False,
    )
    op.create_table(
        "project_progress_snapshots",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("window_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw_pct", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("ema_pct", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("displayed_pct", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column(
            "macro_stage",
            sa.Enum(
                "foundation", "framing", "roofing", "finishing", "approval", name="macro_stage"
            ),
            nullable=False,
        ),
        sa.Column(
            "foundation_pct",
            sa.Numeric(precision=5, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "framing_pct",
            sa.Numeric(precision=5, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "roofing_pct",
            sa.Numeric(precision=5, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "finishing_pct",
            sa.Numeric(precision=5, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "approval_pct",
            sa.Numeric(precision=5, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "eligible_image_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "contributing_image_ids",
            sa.ARRAY(sa.UUID()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "device_weights",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "algorithm_version", sa.String(length=32), server_default="progress-v1", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "raw_pct BETWEEN 0 AND 100 AND ema_pct BETWEEN 0 AND 100 AND displayed_pct BETWEEN 0 AND 100",
            name=op.f("ck_project_progress_snapshots_percentages_range"),
        ),
        sa.CheckConstraint(
            "window_end > window_start", name=op.f("ck_project_progress_snapshots_window_ordered")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_project_progress_snapshots_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_progress_snapshots")),
        sa.UniqueConstraint("project_id", "window_start", name="uq_snapshots_project_window"),
    )
    op.create_index(
        "ix_snapshots_project_id_window_start",
        "project_progress_snapshots",
        ["project_id", "window_start"],
        unique=False,
    )
    op.create_table(
        "reference_assets",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("uploaded_by", sa.UUID(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "blueprint",
                "render_3d",
                "reference_photo",
                "document",
                "inspection_photo",
                name="asset_kind",
            ),
            nullable=False,
        ),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("mime_type", sa.String(length=128), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_public", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("size_bytes > 0", name=op.f("ck_reference_assets_size_positive")),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_reference_assets_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["users.id"],
            name=op.f("fk_reference_assets_uploaded_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reference_assets")),
    )
    op.create_index(
        "ix_reference_assets_project_id", "reference_assets", ["project_id"], unique=False
    )
    op.create_table(
        "remarks",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=True),
        sa.Column(
            "remark_type",
            sa.Enum(
                "system",
                "weather",
                "delay",
                "inactivity",
                "manual",
                "regression",
                name="remark_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.Enum("info", "warning", "critical", name="severity"),
            server_default="info",
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("is_public", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=True),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_from IS NULL OR effective_to >= effective_from",
            name=op.f("ck_remarks_effective_range_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
            name=op.f("fk_remarks_author_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_remarks_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_remarks")),
    )
    op.create_index(
        "ix_remarks_project_id_created_at", "remarks", ["project_id", "created_at"], unique=False
    )
    op.create_table(
        "reports",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("requested_by", sa.UUID(), nullable=False),
        sa.Column(
            "kind", sa.Enum("weekly", "monthly", "custom", name="report_kind"), nullable=False
        ),
        sa.Column("report_format", sa.Enum("pdf", "csv", name="report_format"), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("queued", "processing", "ready", "failed", name="report_status"),
            server_default="queued",
            nullable=False,
        ),
        sa.Column("storage_key", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "requested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("period_end >= period_start", name=op.f("ck_reports_period_ordered")),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_reports_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"],
            ["users.id"],
            name=op.f("fk_reports_requested_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
    )
    op.create_index(
        "ix_reports_project_id_requested_at",
        "reports",
        ["project_id", "requested_at"],
        unique=False,
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("actor_device_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=48), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_device_id"],
            ["devices.id"],
            name=op.f("fk_audit_logs_actor_device_id_devices"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_audit_logs_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(
        "ix_audit_logs_actor_user_id_created_at",
        "audit_logs",
        ["actor_user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_audit_logs_entity_type_entity_id",
        "audit_logs",
        ["entity_type", "entity_id"],
        unique=False,
    )
    op.create_table(
        "device_events",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("battery_mv", sa.Integer(), nullable=True),
        sa.Column("rssi_dbm", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_device_events_device_id_devices"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_device_events")),
    )
    op.create_index(
        "ix_device_events_device_id_created_at",
        "device_events",
        ["device_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "images",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=True),
        sa.Column("filename", sa.String(length=128), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column("preprocessed_key", sa.Text(), nullable=True),
        sa.Column("thumb_key", sa.Text(), nullable=True),
        sa.Column(
            "source",
            sa.Enum("device", "manual_upload", "backfill", name="image_source"),
            server_default="device",
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "preprocessed", "inferred", "rejected", "failed", name="image_status"
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "uploaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("seq_number", sa.Integer(), nullable=True),
        sa.Column("latitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("gps_accuracy_m", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("altitude_m", sa.Numeric(precision=7, scale=2), nullable=True),
        sa.Column("satellites", sa.Integer(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "exif",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "quality_flags",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("rejected_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("char_length(sha256) = 64", name=op.f("ck_images_sha256_length")),
        sa.CheckConstraint(
            "latitude IS NULL OR latitude BETWEEN -90 AND 90", name=op.f("ck_images_latitude_range")
        ),
        sa.CheckConstraint(
            "longitude IS NULL OR longitude BETWEEN -180 AND 180",
            name=op.f("ck_images_longitude_range"),
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_images_device_id_devices"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_images_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_images")),
        sa.UniqueConstraint("project_id", "sha256", name="uq_images_project_sha256"),
    )
    op.create_index(
        "ix_images_device_id_captured_at", "images", ["device_id", "captured_at"], unique=False
    )
    op.create_index(
        "ix_images_project_id_captured_at", "images", ["project_id", "captured_at"], unique=False
    )
    op.create_index("ix_images_status", "images", ["status"], unique=False)
    op.create_table(
        "pairing_tokens",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column(
            "face",
            sa.Enum("front", "front_diagonal", "back", "back_diagonal", name="camera_face"),
            nullable=False,
        ),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("used_by_device_id", sa.UUID(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_pairing_tokens_created_by_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_pairing_tokens_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["used_by_device_id"],
            ["devices.id"],
            name=op.f("fk_pairing_tokens_used_by_device_id_devices"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pairing_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_pairing_tokens_token_hash")),
    )
    op.create_index(
        "ix_pairing_tokens_project_id_expires_at",
        "pairing_tokens",
        ["project_id", "expires_at"],
        unique=False,
    )
    op.create_table(
        "detection_summaries",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("image_id", sa.UUID(), nullable=False),
        sa.Column(
            "counts",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("total_objects", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("inference_ms", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "total_objects >= 0", name=op.f("ck_detection_summaries_total_objects_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["image_id"],
            ["images.id"],
            name=op.f("fk_detection_summaries_image_id_images"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_detection_summaries")),
        sa.UniqueConstraint("image_id", name=op.f("uq_detection_summaries_image_id")),
    )
    op.create_table(
        "detections",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("image_id", sa.UUID(), nullable=False),
        sa.Column("model_id", sa.UUID(), nullable=False),
        sa.Column("class_name", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("bbox_x", sa.Numeric(precision=6, scale=5), nullable=False),
        sa.Column("bbox_y", sa.Numeric(precision=6, scale=5), nullable=False),
        sa.Column("bbox_w", sa.Numeric(precision=6, scale=5), nullable=False),
        sa.Column("bbox_h", sa.Numeric(precision=6, scale=5), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "bbox_x BETWEEN 0 AND 1 AND bbox_y BETWEEN 0 AND 1 AND bbox_w > 0 AND bbox_w <= 1 AND bbox_h > 0 AND bbox_h <= 1",
            name=op.f("ck_detections_bbox_normalised"),
        ),
        sa.CheckConstraint(
            "confidence BETWEEN 0 AND 1", name=op.f("ck_detections_confidence_range")
        ),
        sa.ForeignKeyConstraint(
            ["image_id"],
            ["images.id"],
            name=op.f("fk_detections_image_id_images"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["ai_models.id"],
            name=op.f("fk_detections_model_id_ai_models"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_detections")),
    )
    op.create_index("ix_detections_class_name", "detections", ["class_name"], unique=False)
    op.create_index("ix_detections_image_id", "detections", ["image_id"], unique=False)
    op.create_table(
        "predictions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("image_id", sa.UUID(), nullable=False),
        sa.Column("model_id", sa.UUID(), nullable=False),
        sa.Column("fine_class_index", sa.Integer(), nullable=False),
        sa.Column("fine_class", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column(
            "macro_stage",
            sa.Enum(
                "foundation", "framing", "roofing", "finishing", "approval", name="macro_stage"
            ),
            nullable=False,
        ),
        sa.Column("raw_progress_pct", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("is_eligible", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("low_confidence", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "class_probabilities",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("inference_ms", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence BETWEEN 0 AND 1", name=op.f("ck_predictions_confidence_range")
        ),
        sa.CheckConstraint(
            "fine_class_index BETWEEN 0 AND 9", name=op.f("ck_predictions_fine_class_index_range")
        ),
        sa.CheckConstraint(
            "raw_progress_pct BETWEEN 0 AND 100", name=op.f("ck_predictions_progress_range")
        ),
        sa.ForeignKeyConstraint(
            ["image_id"],
            ["images.id"],
            name=op.f("fk_predictions_image_id_images"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["ai_models.id"],
            name=op.f("fk_predictions_model_id_ai_models"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_predictions")),
        sa.UniqueConstraint("image_id", name=op.f("uq_predictions_image_id")),
    )
    op.create_index("ix_predictions_macro_stage", "predictions", ["macro_stage"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_predictions_macro_stage", table_name="predictions")
    op.drop_table("predictions")
    op.drop_index("ix_detections_image_id", table_name="detections")
    op.drop_index("ix_detections_class_name", table_name="detections")
    op.drop_table("detections")
    op.drop_table("detection_summaries")
    op.drop_index("ix_pairing_tokens_project_id_expires_at", table_name="pairing_tokens")
    op.drop_table("pairing_tokens")
    op.drop_index("ix_images_status", table_name="images")
    op.drop_index("ix_images_project_id_captured_at", table_name="images")
    op.drop_index("ix_images_device_id_captured_at", table_name="images")
    op.drop_table("images")
    op.drop_index("ix_device_events_device_id_created_at", table_name="device_events")
    op.drop_table("device_events")
    op.drop_index("ix_audit_logs_entity_type_entity_id", table_name="audit_logs")
    op.drop_index("ix_audit_logs_actor_user_id_created_at", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index("ix_reports_project_id_requested_at", table_name="reports")
    op.drop_table("reports")
    op.drop_index("ix_remarks_project_id_created_at", table_name="remarks")
    op.drop_table("remarks")
    op.drop_index("ix_reference_assets_project_id", table_name="reference_assets")
    op.drop_table("reference_assets")
    op.drop_index("ix_snapshots_project_id_window_start", table_name="project_progress_snapshots")
    op.drop_table("project_progress_snapshots")
    op.drop_index("ix_project_members_user_id_status", table_name="project_members")
    op.drop_table("project_members")
    op.drop_index("ix_notifications_user_id_read_at", table_name="notifications")
    op.drop_table("notifications")
    op.drop_index("ix_devices_status_last_seen_at", table_name="devices")
    op.drop_index("ix_devices_project_id", table_name="devices")
    op.drop_index(op.f("ix_devices_created_at"), table_name="devices")
    op.drop_table("devices")
    op.drop_index("ix_refresh_tokens_user_id_family_id", table_name="refresh_tokens")
    op.drop_index("ix_refresh_tokens_expires_at", table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index("ix_projects_visibility_status", table_name="projects")
    op.drop_index("ix_projects_owner_id", table_name="projects")
    op.drop_index(
        "ix_projects_name_trgm",
        table_name="projects",
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.drop_index(
        "ix_projects_location_label_trgm",
        table_name="projects",
        postgresql_using="gin",
        postgresql_ops={"location_label": "gin_trgm_ops"},
    )
    op.drop_index("ix_projects_latitude_longitude", table_name="projects")
    op.drop_index(op.f("ix_projects_created_at"), table_name="projects")
    op.drop_table("projects")
    op.drop_index(
        "ix_users_username_trgm",
        table_name="users",
        postgresql_using="gin",
        postgresql_ops={"username": "gin_trgm_ops"},
    )
    op.drop_index(
        "ix_users_full_name_trgm",
        table_name="users",
        postgresql_using="gin",
        postgresql_ops={"full_name": "gin_trgm_ops"},
    )
    op.drop_index(op.f("ix_users_created_at"), table_name="users")
    op.drop_table("users")
    op.drop_index(
        "uq_ai_models_active_per_kind",
        table_name="ai_models",
        postgresql_where=sa.text("is_active"),
    )
    op.drop_table("ai_models")
    # ### end Alembic commands ###

    # Native enum types outlive their tables unless dropped explicitly.
    for enum_type in ENUM_TYPES:
        op.execute(f"DROP TYPE IF EXISTS {enum_type}")

    # Extensions are deliberately NOT dropped: they may be shared with other
    # schemas in the same database, and dropping pg_trgm would invalidate
    # indexes belonging to anything else installed alongside us.
